### ISSUE TITLE
Make trucks deliverable

### ISSUE THREAD

**Issue by guido2** [troublemakers/tmscti.Altis#91]
Make trucks that can transport hq containers deliverable to supply locations.

**Comment by MDTorch** [comment]
- All U.S. trucks are inserted (local branch) - waiting for viewport adjustment by Shaira
- RUS trucks being inserted in the meantime

**Comment by MDTorch** [comment]
Update:
Russian trucks added.
Last step: Update Igiload to transport stuff with the new Kamaz trucks.
